src/config/config.service.ts
src/facility/facility.entity.ts
src/floor/floor.entity.ts
src/inquire/inquire.entity.ts
src/reservation/reservation.entity.ts
src/room/room.entity.ts
src/seat/seat.entity.ts
src/user/user.entity.ts

- 데이터베이스 PostgreSQL에서 MySQL로 변경
- 변경된 데이터베이스 스키마에 맞춰 엔티티 수정

데이터베이스 변경 및 엔티티 수정

---

src/inquire/inquire.entity.ts

Inquire 테이블 변경 이슈 대응
- message 컬럼 길이 변경
- status default 0 설정

[PR] Inquire 테이블 변경

---

src/user/dtos/create-user.dto.ts
src/user/user.entity.ts

User 엔티티에 employee_id 추가
- user.entity.ts 수정
- create-user.dto.ts 대응 수정
Closes #13

feat: User 엔티티에 사원 번호 추가 및 dto 대응

---

src/inquire/inquire.entity.ts
src/notification/notification.entity.ts

Inquire 알림 처리를 위한 Notification 테이블 생성
- notification.entity.ts 작업
Closes #14

[PR] Notification 테이블 생성

---

src/auth/auth.controller.ts
src/common/utils/errors/ErrorMessage.ts
src/config/swagger/setup.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/user/dtos/create-user.dto.ts
src/user/user.entity.ts
src/user/user.service.ts

특정 예약 조회, 특정 예약 삭제 API 추가
- /users/{userId} GET 추가
- /users/{userId} DELETE 추가
Closes #23

[PR] 예약 관련 API 추가 개발

---

src/floor/floor.entity.ts
src/room/dtos/update-room.dto.ts
src/room/room.controller.ts
src/room/room.entity.ts
src/room/room.repository.ts
src/room/room.service.ts
src/seat/dtos/create-seat.dto.ts
src/seat/dtos/update-seat.dto.ts
src/seat/seat.controller.ts
src/seat/seat.entity.ts
src/seat/seat.repository.ts
src/seat/seat.service.ts

좌석, 회의실에서 미구현된 API 구현 마무리
- /seats/{seatId} GET
- /seats/{seatId} PATCH
- /seats/{seatId} DELETE
- /rooms/{roomId} PATCH
- /rooms/{roomId} DELETE
Closes #27

좌석, 회의실 API 구현

---

src/answer/answer.controller.ts
src/answer/answer.entity.ts
src/answer/answer.module.ts
src/answer/answer.repository.ts
src/answer/answer.service.ts
src/answer/dtos/create-answer.dto.ts
src/answer/dtos/search-answer.dto.ts
src/answer/dtos/update-answer.dto.ts
src/app.module.ts
src/common/utils/errors/ErrorMessage.ts
src/config/config.service.ts
src/main.ts
src/notification/notification.entity.ts
src/question/dtos/create-question.dto.ts
src/question/dtos/search-question.dto.ts
src/question/dtos/update-question.dto.ts
src/question/question.controller.ts
src/question/question.entity.ts
src/question/question.module.ts
src/question/question.repository.ts
src/question/question.service.ts
src/user/user.entity.ts

질문 및 답변 CRUD 관련 API 구현
- 질문 및 답변 CRUD 구현
- 질문 및 답변 검색 기능 추가(Query Parameters)
- 기존 Inquire 데이터베이스 설계를 바꿔서 Question, Answer로 분리했습니다.
Closes #22

질문 및 답변 API 구현

---

src/user/dtos/search-user.dto.ts
src/user/user.controller.ts
src/user/user.repository.ts
src/user/user.service.ts

Query Parameters로 유저 검색 기능 구현
- email, name, employeeId, department, position 으로 검색 가능하도록 API 구현
Closes #33

User 검색 API 구현

---

src/auth/auth.controller.ts
src/config/config.service.ts
src/config/swagger/setup.ts
src/user/user.controller.ts

User 인증 및 권한 설정
- User 인증 및 권한 설정
- 인증 및 권한 문서화
Closes #34

User 인증 및 권한 설정

---

src/floor/floor.entity.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/room/room.entity.ts
src/seat/seat.entity.ts

좌석, 회의실 정보 및 관련 층 정보를 함께 반환
Closes #42

[PR] 예약 조회 시 관련 정보 추가 반환

---

src/reservation/dtos/create-reservation.dto.ts
src/reservation/dtos/create-room-reservation.dto.ts
src/reservation/dtos/create-seat-reservation.dto.ts
src/reservation/reservation.entity.ts
src/reservation/reservation.module.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/room/room.entity.ts
src/seat/seat.entity.ts

예약 관련 시 정보가 제대로 들어가지 않는 오류 수정
- 좌석, 회의실 예약 시 좌석, 회의실이 외래키에 들어가지 않는 오류 수정
- 예약과 좌석, 회의실 1대1 맵핑에서 N대1 맵핑으로 변경
- 예약 생성 dto에 Mapped Types 적용

[PR] 예약 관련 오류 수정

---

src/reservation/reservation.module.ts
src/reservation/reservation.service.ts

transaction 코드 변경
- 회의실 예약 생성 실패 혹은 참석자 정보가 올바르지 않은 경우 transaction이 적용되도록 수정
Closes #48

[PR] 예약 실패 시 transaction이 되지 않는 오류 수정

---

src/auth/auth.module.ts
src/reservation/dtos/search-reservation.dto.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/room/room.repository.ts
src/room/room.service.ts
src/seat/seat.repository.ts
src/seat/seat.service.ts

개발자 미팅 후 나온 피드백 반영
- JWT 토큰 만료 기간 1일에서 30일로 변경(개발용 임시)
- 좌석 및 회의실 정보 반환 시 층 정보도 함께 반환
- 예약을 사용자 id로 검색할 수 있도록 구현

[PR] 211110 피드백 반영

---

src/question/question.repository.ts

[PR] 질문 검색 시 답변 정보도 같이 반환하도록 수정

---

src/facility/dtos/search-facility.dto.ts
src/facility/facility.controller.ts
src/facility/facility.repository.ts
src/facility/facility.service.ts
src/room/dtos/search-room.dto.ts
src/room/room.controller.ts
src/room/room.repository.ts
src/room/room.service.ts
src/seat/dtos/search-seat.dto.ts
src/seat/seat.controller.ts
src/seat/seat.repository.ts
src/seat/seat.service.ts

floorId로 검색할 수 있도록 변경
- /seats, /rooms, /facilities에 각각 search 엔드포인트를 추가해서 query parameters로 받을 수 있도록 구현

[PR] 좌석, 회의실, 시설 검색 API

---

.gitignore
package-lock.json
package.json
src/config/config.service.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/task/task.service.ts

esl tag 데이터 파싱 csv 파일 생성
- 5분 간격으로 esl 태그 갱신에 필요한 데이터를 csv 파일로 생성
- ftp로 esl gateway에 보내는 로직은 미완성
- typeorm timezone 설정

[PR] esl tag 데이터 파싱 csv 파일 생성

---

src/reservation/reservation.repository.ts
src/room/room.entity.ts
src/seat/seat.entity.ts
src/task/task.service.ts

좌석, 회의실 테이블에 esl tag id를 저장할 수 있는 컬럼 추가
Closes #62

feat: 좌석, 회의실 테이블에 esl tag id를 저장할 수 있는 컬럼 추가

---

src/user/user.service.ts

회원 정보 수정 시 비밀번호가 해싱되지 않는 오류 수정
Closes #65

[PR] 회원 정보 수정 시 비밀번호가 해싱되지 않는 오류 수정

---

src/question/question.module.ts
src/question/question.repository.ts
src/question/question.service.ts

[PR] 질문 삭제 시 연관 답변도 삭제

---

src/common/utils/errors/http-message.enum.ts
src/question/question.entity.ts
src/question/question.service.ts

답변없는 질문 삭제 및 userId entity 추가
답변없는 질문 try catch 문 조건 추가
질문 API에 userId도 GET 할 수 있도록 추가
질문 삭제 에러메세지 수정
Closes

[PR] 답변없는 질문 삭제 및 userId entity 추가

---

.gitignore
package-lock.json
package.json
src/question/question.repository.ts
src/question/question.service.ts
src/reservation/dtos/create-reservation.dto.ts
src/reservation/dtos/create-room-reservation.dto.ts
src/reservation/dtos/create-seat-reservation.dto.ts
src/reservation/dtos/search-reservation.dto.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.entity.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/task/task.module.ts
src/task/task.service.ts

ESL 관련 *.csv 파싱 및 ftp 관련 작업
- 예약 상태를 확인해서 *.csv 파싱
- 생성된 *.csv 파일을 esl gateway에 ftp로 전송
- 테스트는 완료 했으나 esl gateway 오류로 현재 전송은 안되는 상태

[PR] ESL 관련 작업

---

src/answer/answer.service.ts
src/common/utils/errors/http-message.enum.ts
src/question/question.entity.ts
src/question/question.service.ts

질문 답변 시 답변 상태 update
질문 답변시 status 값 1로 update
Closes

[PR] 질문 답변 시 답변 상태 update

---

src/reservation/dtos/search-reservation.dto.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts

[PR] 회의실 예약 테이블 조회 API

---

src/reservation/dtos/create-reservation.dto.ts
src/reservation/dtos/create-room-reservation.dto.ts
src/reservation/dtos/create-seat-reservation.dto.ts
src/reservation/dtos/search-reservation.dto.ts
src/reservation/reservation.controller.ts
src/reservation/reservation.repository.ts
src/reservation/reservation.service.ts
src/task/task.service.ts

회의실 예약 테이블
- 회의실 예약 테이블을 만들어서 응답으로 보내줌
- 회의실 예약 상태를 검사하는 스케줄러 주기를 3분으로 조절

[PR] 회의실 예약 테이블

---

src/reservation/reservation.repository.ts
src/task/task.module.ts
src/task/task.service.ts

[PR] ESL converter 구현

---

package.json
src/reservation/reservation.entity.ts
src/reservation/reservation.repository.ts
src/room/room.entity.ts
src/room/room.repository.ts
src/seat/seat.entity.ts
src/seat/seat.repository.ts
src/task/task.module.ts
src/task/task.service.ts

[PR] ESL converter 로직 변경

---

src/common/utils/errors/http-message.enum.ts
src/reservation/dtos/create-reservation.dto.ts
src/reservation/dtos/create-seat-reservation.dto.ts
src/reservation/reservation.service.ts
src/room/dtos/create-room.dto.ts
src/room/room.entity.ts
src/seat/dtos/create-seat.dto.ts
src/seat/seat.entity.ts
src/seat/seat.repository.ts
src/user/user.entity.ts
src/user/user.service.ts

[PR] 이슈 해결 배포
